# 🧩 Notebook-01: NumPy Array Basics — Creation, Types, and Attributes
python

In [1]:
# ✅ Compatible with Jupyter Notebook environment
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
SCRIPT_DIR = PROJECT_ROOT / "scripts"

if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

# Now import
import numpy as np
from array_utils import (
    describe_array,
    array_flags,
    print_array_with_header,
    create_identity_matrix,
    generate_range
)

print("🔢 NumPy Array Basics\n")

🔢 NumPy Array Basics



In [2]:
# ✅ 1. Creating arrays from lists/tuples
list_data = [1, 2, 3]
array_from_list = np.array(list_data)
print_array_with_header(array_from_list, "Array from list")
describe_array(array_from_list)


🔹 Array from list
[1 2 3]
🔍 Array Summary:
  Shape     : (3,)
  Size      : 3
  Ndim      : 1
  Dtype     : int64
  Itemsize  : 8
  Nbytes    : 24


{'shape': (3,),
 'size': 3,
 'ndim': 1,
 'dtype': dtype('int64'),
 'itemsize': 8,
 'nbytes': 24}

In [3]:
# ✅ 2. Built-in arrays
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 3), 7)
empty = np.empty((2, 3))

print_array_with_header(zeros, "Zeros")
print_array_with_header(ones, "Ones")
print_array_with_header(full, "Full (value=7)")
print_array_with_header(empty, "Empty (uninitialized)")


🔹 Zeros
[[0. 0. 0.]
 [0. 0. 0.]]

🔹 Ones
[[1. 1. 1.]
 [1. 1. 1.]]

🔹 Full (value=7)
[[7 7 7]
 [7 7 7]]

🔹 Empty (uninitialized)
[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# ✅ 3. Ranges
arange_ex = generate_range(0, 10, 2)
linspace_ex = np.linspace(0, 1, 5)
logspace_ex = np.logspace(1, 3, 3)

print_array_with_header(arange_ex, "Arange (0 to 10 step 2)")
print_array_with_header(linspace_ex, "Linspace (0 to 1, 5 pts)")
print_array_with_header(logspace_ex, "Logspace (10^1 to 10^3)")


🔹 Arange (0 to 10 step 2)
[0 2 4 6 8]

🔹 Linspace (0 to 1, 5 pts)
[0.   0.25 0.5  0.75 1.  ]

🔹 Logspace (10^1 to 10^3)
[  10.  100. 1000.]


In [5]:
# ✅ 4. Identity and Diagonal
eye = np.eye(3)
identity = create_identity_matrix(3)
diag = np.diag([1, 2, 3])

print_array_with_header(eye, "Eye (ones on diagonal)")
print_array_with_header(identity, "Identity (using helper)")
print_array_with_header(diag, "Diagonal from list")


🔹 Eye (ones on diagonal)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

🔹 Identity (using helper)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

🔹 Diagonal from list
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [6]:
# ✅ 5. Random arrays
rand = np.random.rand(2, 2)
randn = np.random.randn(2, 2)
randint = np.random.randint(1, 10, (2, 3))

print_array_with_header(rand, "Random Uniform (0–1)")
print_array_with_header(randn, "Random Normal (mean=0)")
print_array_with_header(randint, "Random Integers (1–9)")


🔹 Random Uniform (0–1)
[[0.40031123 0.30745412]
 [0.3673808  0.77821803]]

🔹 Random Normal (mean=0)
[[-0.41529017 -1.51735392]
 [ 2.39554745  1.57162881]]

🔹 Random Integers (1–9)
[[9 9 1]
 [6 1 9]]


In [7]:
# ✅ 6. Attributes & Flags
describe_array(rand)

🔍 Array Summary:
  Shape     : (2, 2)
  Size      : 4
  Ndim      : 2
  Dtype     : float64
  Itemsize  : 8
  Nbytes    : 32


{'shape': (2, 2),
 'size': 4,
 'ndim': 2,
 'dtype': dtype('float64'),
 'itemsize': 8,
 'nbytes': 32}

In [8]:
array_flags(rand)

🧠 Memory Flags:
  - C_CONTIGUOUS: True
  - F_CONTIGUOUS: False
  - OWNDATA: True
  - WRITEABLE: True
  - ALIGNED: True
  - WRITEBACKIFCOPY: False


{'C_CONTIGUOUS': True,
 'F_CONTIGUOUS': False,
 'OWNDATA': True,
 'WRITEABLE': True,
 'ALIGNED': True,
 'WRITEBACKIFCOPY': False}