# 🧩 Title: NumPy Array Basics — Creation, Types, and Attributes
python

In [1]:
import numpy as np
print("🔢 Numpy Array Basics\n")

🔢 Numpy Array Basics



In [2]:
# ✅ 1. Creating arrays from lists/tuples
list_data = [1, 2, 3]
array_from_list = np.array(list_data)
print("Array from list: ", array_from_list)

Array from list:  [1 2 3]


In [3]:

# ✅ 2. Check type, shape, and dtype
print("Type:", type(array_from_list))
print("Shape:", array_from_list.shape)
print("Data type:", array_from_list.dtype)

Type: <class 'numpy.ndarray'>
Shape: (3,)
Data type: int64


In [4]:
# ✅ 3. Creating arrays with built-in functions
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 3), 7)
empty = np.empty((2, 3))
print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nFull:\n", full)
print("\nEmpty:\n", empty)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full:
 [[7 7 7]
 [7 7 7]]

Empty:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# ✅ 4. Ranges
arange_ex = np.arange(0, 10, 2)
linspace_ex = np.linspace(0, 1, 5)
logspace_ex = np.logspace(1, 3, 3)
print("\nArange:", arange_ex)
print("Linspace:", linspace_ex)
print("Logspace:", logspace_ex)


Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Logspace: [  10.  100. 1000.]


In [6]:
# ✅ 5. Identity and Diagonal
eye = np.eye(3)
identity = np.identity(3)
diag = np.diag([1, 2, 3])
print("\nEye:\n", eye)
print("Identity:\n", identity)
print("Diagonal:\n", diag)


Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
# ✅ 6. Random arrays
rand = np.random.rand(2, 2)
randn = np.random.randn(2, 2)
randint = np.random.randint(1, 10, (2, 3))
print("\nRandom Uniform:\n", rand)
print("Random Normal:\n", randn)
print("Random Int:\n", randint)


Random Uniform:
 [[0.68707746 0.18008416]
 [0.84675494 0.30017555]]
Random Normal:
 [[ 0.62281894 -0.98219386]
 [-0.77804906  0.5167055 ]]
Random Int:
 [[5 9 4]
 [6 3 5]]


In [ ]:
# ✅ 7. Attributes of arrays
print("\nShape:", rand.shape)
print("Size:", rand.size)
print("Ndim:", rand.ndim)
print("Itemsize:", rand.itemsize)
print("Total bytes:", rand.nbytes)
print("Flags:\n", rand.flags) # array metadata


Shape: (2, 2)
Size: 4
Ndim: 2
Itemsize: 8
Total bytes: 32
Flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

