# 🧩 Title: Indexing, Slicing, and Fancy Selection in NumPy
python

In [1]:
import numpy as np
print("🔍 NumPy Indexing, Slicing & Selection\n")

🔍 NumPy Indexing, Slicing & Selection



In [2]:
# ✅ 1. Basic indexing
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("arr[0] =", arr[0])
print("arr[-1] =", arr[-1])

Original array: [10 20 30 40 50]
arr[0] = 10
arr[-1] = 50


In [3]:
# ✅ 2. Slicing (1D)
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("arr[0] =", arr[0])
print("arr[-1] =", arr[-1])

Original array: [10 20 30 40 50]
arr[0] = 10
arr[-1] = 50


In [4]:
# ✅ 3. 2D array indexing
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("\nMatrix:\n", mat)
print("mat[0][1] =", mat[0][1])    # or mat[0, 1]
print("mat[2, :] =", mat[2, :])    # 3rd row
print("mat[:, 1] =", mat[:, 1])    # 2nd column


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mat[0][1] = 2
mat[2, :] = [7 8 9]
mat[:, 1] = [2 5 8]


In [5]:
# ✅ 4. Boolean indexing
arr = np.array([3, 7, 1, 8, 5])
mask = arr > 4
print("\nBoolean mask:", mask)
print("Filtered:", arr[mask])
print("Shortcut:", arr[arr > 4])


Boolean mask: [False  True False  True  True]
Filtered: [7 8 5]
Shortcut: [7 8 5]


In [6]:
# ✅ 5. Fancy indexing
indices = [0, 2, 4]
print("\nFancy Indexing:", arr[indices])


Fancy Indexing: [3 1 5]


In [7]:
# ✅ 6. Modify elements using indexing
arr[0:2] = 99
print("Modified array:", arr)

Modified array: [99 99  1  8  5]


In [8]:
# ✅ 7. Using `np.where`
data = np.array([5, 10, 15, 20])
print("\nWhere condition:", np.where(data > 10, "High", "Low"))


Where condition: ['Low' 'Low' 'High' 'High']


In [9]:
# ✅ 8. `np.nonzero()` and `np.count_nonzero()`
z = np.array([0, 1, 0, 2, 3])
print("\nNon-zero indices:", np.nonzero(z))
print("Count of non-zero:", np.count_nonzero(z))


Non-zero indices: (array([1, 3, 4]),)
Count of non-zero: 3


In [10]:
# ✅ 9. Multidimensional fancy indexing
x = np.array([[11, 12],
              [21, 22],
              [31, 32]])
row_idx = [0, 1, 2]
col_idx = [1, 0, 1]
print("\nAdvanced indexing:", x[row_idx, col_idx])


Advanced indexing: [12 21 32]


In [11]:
# ✅ 10. Using .take() and .put()
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print("Take indices 0,2,4:", arr.take(indices))

# Now update values at index 1 and 3
arr.put([1, 3], [99, 88])
print("After put at indices 1,3:", arr)

Take indices 0,2,4: [10 30 50]
After put at indices 1,3: [10 99 30 88 50]
