# 🧩 Notebook-02: Indexing, Slicing, and Fancy Selection in NumPy
python

In [1]:
# 📁 Set up project root and scripts path
import sys
from pathlib import Path

# Automatically find the project root (assuming you're in notebooks/ or similar)
CURRENT_NOTEBOOK = Path().resolve()
PROJECT_ROOT = CURRENT_NOTEBOOK.parent.parent  # Adjust depending on notebook location
SCRIPT_DIR = PROJECT_ROOT / "scripts"

# 🔧 Add scripts/ to sys.path
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

# ✅ Now import utilities
import numpy as np
import pandas as pd
from array_utils import (
    describe_array, array_summary_table, print_array_with_header
)

print("🔍 NumPy Indexing, Slicing & Selection\n")


ModuleNotFoundError: No module named 'array_utils'

In [ ]:
# ✅ 1. Basic indexing
arr = np.array([10, 20, 30, 40, 50])
print_array_with_header(arr, "Original Array (1D)")

print("arr[0] =", arr[0])
print("arr[-1] =", arr[-1])
describe_array(arr)


🔹 Original Array (1D)
[10 20 30 40 50]
arr[0] = 10
arr[-1] = 50
🔍 Array Summary:
  Shape     : (5,)
  Size      : 5
  Ndim      : 1
  Dtype     : int64
  Itemsize  : 8
  Nbytes    : 40


{'shape': (5,),
 'size': 5,
 'ndim': 1,
 'dtype': dtype('int64'),
 'itemsize': 8,
 'nbytes': 40}

In [ ]:
# ✅ 2. Slicing (1D)
print("arr[1:4] =", arr[1:4])
print("arr[:3] =", arr[:3])
print("arr[::2] =", arr[::2])  # Step slicing

arr[1:4] = [20 30 40]
arr[:3] = [10 20 30]
arr[::2] = [10 30 50]


In [ ]:
# ✅ 3. 2D array indexing
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print_array_with_header(mat, "Original 2D Array")

print("mat[0, 1] =", mat[0, 1])
print("mat[2, :] =", mat[2, :])
print("mat[:, 1] =", mat[:, 1])
describe_array(mat)


🔹 Original 2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
mat[0, 1] = 2
mat[2, :] = [7 8 9]
mat[:, 1] = [2 5 8]
🔍 Array Summary:
  Shape     : (3, 3)
  Size      : 9
  Ndim      : 2
  Dtype     : int64
  Itemsize  : 8
  Nbytes    : 72


{'shape': (3, 3),
 'size': 9,
 'ndim': 2,
 'dtype': dtype('int64'),
 'itemsize': 8,
 'nbytes': 72}

In [ ]:
# ✅ 4. Boolean indexing
arr = np.array([3, 7, 1, 8, 5])
mask = arr > 4

print_array_with_header(mask, "Boolean Mask (arr > 4)")
print_array_with_header(arr[mask], "Filtered using mask")
print("Shortcut:", arr[arr > 4])


🔹 Boolean Mask (arr > 4)
[False  True False  True  True]

🔹 Filtered using mask
[7 8 5]
Shortcut: [7 8 5]


In [ ]:
# ✅ 5. Fancy indexing
indices = [0, 2, 4]
print("Fancy Indexing:", arr[indices])

Fancy Indexing: [3 1 5]


In [ ]:
# ✅ 6. Modify elements using indexing
arr[0:2] = 99
print_array_with_header(arr, "Modified Array (arr[0:2] = 99)")


🔹 Modified Array (arr[0:2] = 99)
[99 99  1  8  5]


In [ ]:
# ✅ 7. Using `np.where`
data = np.array([5, 10, 15, 20])
print("Condition Result:", np.where(data > 10, "High", "Low"))

Condition Result: ['Low' 'Low' 'High' 'High']


In [ ]:
# ✅ 8. `np.nonzero()` and `np.count_nonzero()`
z = np.array([0, 1, 0, 2, 3])
print("Non-zero indices:", np.nonzero(z)[0])
print("Count of non-zero elements:", np.count_nonzero(z))

Non-zero indices: [1 3 4]
Count of non-zero elements: 3


In [ ]:
# ✅ 9. Multidimensional fancy indexing
x = np.array([[11, 12], [21, 22], [31, 32]])
row_idx = [0, 1, 2]
col_idx = [1, 0, 1]

print("Advanced indexing result:", x[row_idx, col_idx])

Advanced indexing result: [12 21 32]


In [ ]:
# ✅ 10. Using .take() and .put()
arr = np.array([10, 20, 30, 40, 50])
print("Take [0, 2, 4]:", arr.take([0, 2, 4]))

arr.put([1, 3], [99, 88])
print("After put at indices 1 and 3:", arr)

Take [0, 2, 4]: [10 30 50]
After put at indices 1 and 3: [10 99 30 88 50]


In [ ]:
# Final Summary Table of Arrays
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3, 4)
arr3 = np.array([[5, 6], [7, 8]])

summary = array_summary_table(arr1, arr2, arr3, names=["1D", "2D", "2x2"])
print("\n📊 Summary Table of Arrays:")
display(summary)



📊 Summary Table of Arrays:


Name   Shape  Size  Dtype  Nbytes
0   1D   (10,)    10  int64      80
1   2D  (3, 4)    12  int64      96
2  2x2  (2, 2)     4  int64      32