# 🧩 Notebook-03: Array Reshaping, Stacking, Transposing, and Broadcasting

In [1]:
# ✅ Setup
import sys
from pathlib import Path
import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
SCRIPT_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from array_utils import (
    describe_array, array_summary_table, print_array_with_header
)

print("🔀 NumPy Array Manipulation\n")

🔀 NumPy Array Manipulation



In [2]:
# ✅ 1. Reshaping
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print_array_with_header(arr, "Original")
print_array_with_header(reshaped, "Reshaped (3x4)")


🔹 Original
[ 0  1  2  3  4  5  6  7  8  9 10 11]

🔹 Reshaped (3x4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
# ✅ 2. Flattening vs Ravel
print_array_with_header(reshaped.flatten(), "Flattened (Copy)")
print_array_with_header(reshaped.ravel(), "Ravel (View)")


🔹 Flattened (Copy)
[ 0  1  2  3  4  5  6  7  8  9 10 11]

🔹 Ravel (View)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# ✅ 3. Expand/Squeeze dimensions
a = np.array([1, 2, 3])
print_array_with_header(a, "Original Shape")
a_expanded = np.expand_dims(a, axis=0)
print_array_with_header(a_expanded, "After expand_dims (axis=0)")
a_squeezed = np.squeeze(a_expanded)
print_array_with_header(a_squeezed, "After squeeze")


🔹 Original Shape
[1 2 3]

🔹 After expand_dims (axis=0)
[[1 2 3]]

🔹 After squeeze
[1 2 3]


In [5]:
# ✅ 4. Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print_array_with_header(np.concatenate((a, b), axis=0), "Concat axis=0")
print_array_with_header(np.concatenate((a.T, b.T), axis=1), "Concat axis=1")


🔹 Concat axis=0
[[1 2]
 [3 4]
 [5 6]]

🔹 Concat axis=1
[[1 3 5]
 [2 4 6]]


In [6]:
# ✅ 5. Stacking
print_array_with_header(np.vstack((a, b)), "Vertical Stack")
print_array_with_header(np.hstack((a.T, b.T)), "Horizontal Stack")


🔹 Vertical Stack
[[1 2]
 [3 4]
 [5 6]]

🔹 Horizontal Stack
[[1 3 5]
 [2 4 6]]


In [7]:
# ✅ 6. Stack along new axis
print_array_with_header(np.stack((a, a), axis=0), "Stacked (new axis=0)")


🔹 Stacked (new axis=0)
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [8]:
# ✅ 7. Splitting arrays
arr = np.arange(8)
print_array_with_header(arr, "Original for Splitting")
print("Split into 2:", np.split(arr, 2))
print("Unequal split (array_split):", np.array_split(arr, 3))


🔹 Original for Splitting
[0 1 2 3 4 5 6 7]
Split into 2: [array([0, 1, 2, 3]), array([4, 5, 6, 7])]
Unequal split (array_split): [array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]


In [9]:
# ✅ 8. Transpose and .T
mat = np.array([[1, 2, 3], [4, 5, 6]])
print_array_with_header(mat, "Original Matrix")
print_array_with_header(mat.T, "Transposed via .T")
print_array_with_header(np.transpose(mat), "Transposed via np.transpose")


🔹 Original Matrix
[[1 2 3]
 [4 5 6]]

🔹 Transposed via .T
[[1 4]
 [2 5]
 [3 6]]

🔹 Transposed via np.transpose
[[1 4]
 [2 5]
 [3 6]]


In [10]:
# ✅ 9. Swapping axes
tensor = np.zeros((2, 3, 4))
print("Original shape:", tensor.shape)
swapped = np.swapaxes(tensor, 0, 2)
print("After swapaxes(0, 2):", swapped.shape)

Original shape: (2, 3, 4)
After swapaxes(0, 2): (4, 3, 2)


In [11]:
# ✅ 10. Repeating & Tiling
a = np.array([[1, 2]])
print_array_with_header(np.repeat(a, 3), "Repeat elements")
print_array_with_header(np.repeat(a, 2, axis=0), "Repeat rows")
print_array_with_header(np.tile(a, (2, 3)), "Tiled array (2x3)")


🔹 Repeat elements
[1 1 1 2 2 2]

🔹 Repeat rows
[[1 2]
 [1 2]]

🔹 Tiled array (2x3)
[[1 2 1 2 1 2]
 [1 2 1 2 1 2]]


In [12]:
# ✅ 11. Padding
pad_arr = np.array([[1, 2], [3, 4]])
padded = np.pad(pad_arr, pad_width=1, mode='constant', constant_values=0)
print_array_with_header(pad_arr, "Original (for Padding)")
print_array_with_header(padded, "Padded array")


🔹 Original (for Padding)
[[1 2]
 [3 4]]

🔹 Padded array
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [13]:
# ✅ 12. Resize (with caution)
resized = np.resize(arr, (3, 5))
print_array_with_header(resized, "Resized (shape 3x5)")


🔹 Resized (shape 3x5)
[[0 1 2 3 4]
 [5 6 7 0 1]
 [2 3 4 5 6]]
