# 🧩 Title: Array Reshaping, Stacking, Transposing, and Broadcasting

In [1]:
import numpy as np
print("🔀 NumPy Array Manipulation\n")

🔀 NumPy Array Manipulation



In [2]:
# ✅ 1. Reshaping
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("Original:", arr)
print("Reshaped (3x4):\n", reshaped)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
# ✅ 2. Flattening vs Ravel
print("\nFlattened:", reshaped.flatten())
print("Ravel (view):", reshaped.ravel())


Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel (view): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# ✅ 3. Expand/Squeeze dimensions
a = np.array([1, 2, 3])
print("\nOriginal shape:", a.shape)
a_expanded = np.expand_dims(a, axis=0)
print("After expand_dims (axis=0):", a_expanded.shape)
a_squeezed = np.squeeze(a_expanded)
print("After squeeze:", a_squeezed.shape)


Original shape: (3,)
After expand_dims (axis=0): (1, 3)
After squeeze: (3,)


In [5]:
# ✅ 4. Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_axis0 = np.concatenate((a, b), axis=0)
concat_axis1 = np.concatenate((a.T, b.T), axis=1)
print("\nConcat axis=0:\n", concat_axis0)
print("Concat axis=1:\n", concat_axis1)


Concat axis=0:
 [[1 2]
 [3 4]
 [5 6]]
Concat axis=1:
 [[1 3 5]
 [2 4 6]]


In [6]:
# ✅ 5. Stacking
v_stack = np.vstack((a, b))
h_stack = np.hstack((a.T, b.T))
print("\nVertical stack:\n", v_stack)
print("Horizontal stack:\n", h_stack)


Vertical stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal stack:
 [[1 3 5]
 [2 4 6]]


In [7]:
# ✅ 6. Stack along new axis
stacked = np.stack((a, a), axis=0)
print("\nStacked (new axis=0):\n", stacked)


Stacked (new axis=0):
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [8]:
# ✅ 7. Splitting arrays
arr = np.arange(8)
print("\nOriginal:", arr)
print("Split into 2:", np.split(arr, 2))
print("Unequal split (array_split):", np.array_split(arr, 3))


Original: [0 1 2 3 4 5 6 7]
Split into 2: [array([0, 1, 2, 3]), array([4, 5, 6, 7])]
Unequal split (array_split): [array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]


In [9]:
# ✅ 8. Transpose and .T
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal Matrix:\n", mat)
print("Transposed (via .T):\n", mat.T)
print("Transposed (via np.transpose):\n", np.transpose(mat))


Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed (via .T):
 [[1 4]
 [2 5]
 [3 6]]
Transposed (via np.transpose):
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
# ✅ 9. Swapping axes
tensor = np.zeros((2, 3, 4))
print("\nOriginal shape:", tensor.shape)
swapped = np.swapaxes(tensor, 0, 2)
print("After swapaxes(0, 2):", swapped.shape)


Original shape: (2, 3, 4)
After swapaxes(0, 2): (4, 3, 2)


In [11]:
# ✅ 10. Repeating & Tiling
a = np.array([[1, 2]])
print("\nRepeat elements:", np.repeat(a, 3))
print("Repeat rows:", np.repeat(a, 2, axis=0))
print("Tiled:\n", np.tile(a, (2, 3)))


Repeat elements: [1 1 1 2 2 2]
Repeat rows: [[1 2]
 [1 2]]
Tiled:
 [[1 2 1 2 1 2]
 [1 2 1 2 1 2]]


In [12]:
# ✅ 11. Padding
pad_arr = np.array([[1, 2], [3, 4]])
padded = np.pad(pad_arr, pad_width=1, mode='constant', constant_values=0)
print("\nOriginal:\n", pad_arr)
print("Padded:\n", padded)


Original:
 [[1 2]
 [3 4]]
Padded:
 [[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [13]:
# ✅ 12. Resize (can distort data shape, use with care)
resized = np.resize(arr, (3, 5))
print("\nResized:\n", resized)


Resized:
 [[0 1 2 3 4]
 [5 6 7 0 1]
 [2 3 4 5 6]]
