# 🧩 Notebook-04: Math Operations, Aggregations, and Broadcasting

In [1]:
import sys
from pathlib import Path

# ✅ Setup project path
PROJECT_ROOT = Path.cwd().parent
SCRIPT_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

# ✅ Imports
import numpy as np
import pandas as pd

from math_utils import (
    add_arrays, subtract_arrays, multiply_arrays, divide_arrays, modulo_arrays, floor_divide_arrays,
    power_array, round_array, floor_array, ceil_array, trunc_array,
    exp_array, natural_log, base10_log,
    sqrt_array, cbrt_array,
    sin_array, cos_array, arcsin_array, to_degrees, to_radians,
    clip_array, absolute_array, cumulative_sum, cumulative_product
)

from aggregation_utils import (
    array_sum, array_mean, array_min, array_max, array_std, array_var,
    axis_sum, axis_mean, axis_min, axis_max, axis_std, axis_var
)

print("🧮 NumPy Math Operations, Aggregations & Broadcasting\n")

🧮 NumPy Math Operations, Aggregations & Broadcasting



In [2]:
# ✅ 1. Element-wise arithmetic
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b:", add_arrays(a, b))
print("a - b:", subtract_arrays(a, b))
print("a * b:", multiply_arrays(a, b))
print("a / b:", divide_arrays(a, b))
print("a % b:", modulo_arrays(a, b))
print("a // b:", floor_divide_arrays(a, b))
print("a ** 2:", power_array(a, 2))

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a % b: [1 2 3]
a // b: [0 0 0]
a ** 2: [1 4 9]


In [3]:
# ✅ 2. Aggregate functions
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:\n", mat)
print("Sum:", array_sum(mat))
print("Mean:", array_mean(mat))
print("Min:", array_min(mat))
print("Max:", array_max(mat))
print("Std Dev:", array_std(mat))
print("Variance:", array_var(mat))


Matrix:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Mean: 3.5
Min: 1
Max: 6
Std Dev: 1.707825127659933
Variance: 2.9166666666666665


In [4]:
# ✅ 3. Axis-based aggregations
print("\nSum along axis 0 (columns):", axis_sum(mat, axis=0))
print("Sum along axis 1 (rows):", axis_sum(mat, axis=1))
print("\nMean along axis 0 (columns):", axis_mean(mat, axis=0))
print("Mean along axis 1 (rows):", axis_mean(mat, axis=1))
print("\nMin along axis 0 (columns):", axis_min(mat, axis=0))
print("Min along axis 1 (rows):", axis_min(mat, axis=1))
print("\nMax along axis 0 (columns):", axis_max(mat, axis=0))
print("Max along axis 1 (rows):", axis_max(mat, axis=1))
print("\nStd Dev along axis 0 (columns):", axis_std(mat, axis=0))
print("Std Dev along axis 1 (rows):", axis_std(mat, axis=1))


Sum along axis 0 (columns): [5 7 9]
Sum along axis 1 (rows): [ 6 15]

Mean along axis 0 (columns): [2.5 3.5 4.5]
Mean along axis 1 (rows): [2. 5.]

Min along axis 0 (columns): [1 2 3]
Min along axis 1 (rows): [1 4]

Max along axis 0 (columns): [4 5 6]
Max along axis 1 (rows): [3 6]

Std Dev along axis 0 (columns): [1.5 1.5 1.5]
Std Dev along axis 1 (rows): [0.81649658 0.81649658]


In [5]:
# ✅ 4. Rounding
arr = np.array([1.234, 5.678, 9.876])
print("\nRounded (2 decimals):", round_array(arr, 2))
print("Floor:", floor_array(arr))
print("Ceil:", ceil_array(arr))
print("Trunc:", trunc_array(arr))


Rounded (2 decimals): [1.23 5.68 9.88]
Floor: [1. 5. 9.]
Ceil: [ 2.  6. 10.]
Trunc: [1. 5. 9.]


In [6]:
# ✅ 5. Exponentials and logarithms
arr = np.array([1, np.e, np.e**2])
print("\nOriginal:", arr)
print("Natural log:", natural_log(arr))
print("Base-10 log:", base10_log(arr))
print("Exponential:", exp_array(arr))


Original: [1.         2.71828183 7.3890561 ]
Natural log: [0. 1. 2.]
Base-10 log: [0.         0.43429448 0.86858896]
Exponential: [   2.71828183   15.15426224 1618.17799191]


In [7]:
# ✅ 6. Roots and powers
nums = np.array([4, 9, 16])
print("\nSqrt:", sqrt_array(nums))
print("Cube root:", cbrt_array(nums))
print("Power (nums^3):", power_array(nums, 3))


Sqrt: [2. 3. 4.]
Cube root: [1.58740105 2.08008382 2.5198421 ]
Power (nums^3): [  64  729 4096]


In [8]:
# ✅ 7. Trigonometry
angles = np.array([0, np.pi/2, np.pi])
print("\nSine:", sin_array(angles))
print("Cosine:", cos_array(angles))
print("Arcsin(1):", arcsin_array(np.array([1.0])))
print("Degrees:", to_degrees(angles))
print("Radians:", to_radians([0, 90, 180]))


Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Arcsin(1): [1.57079633]
Degrees: [  0.  90. 180.]
Radians: [0.         1.57079633 3.14159265]


In [9]:
# ✅ 8. Broadcasting example
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20, 30])     # shape (3,)
broadcasted = a + b
print("\nBroadcasting:\n", broadcasted)


Broadcasting:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [10]:
# ✅ 9. Clipping and absolute
arr = np.array([-10, -2, 0, 4, 12])
print("\nClipped (0 to 10):", clip_array(arr, 0, 10))
print("Absolute:", absolute_array(arr))


Clipped (0 to 10): [ 0  0  0  4 10]
Absolute: [10  2  0  4 12]


In [11]:
# ✅ 10. Cumulative operations
print("\nCumulative sum:", cumulative_sum(arr))
print("Cumulative product:", cumulative_product(arr + 11))  # make all positive to avoid 0


Cumulative sum: [-10 -12 -12  -8   4]
Cumulative product: [    1     9    99  1485 34155]
