# 🧩 Title: Math Operations, Aggregations, and Broadcasting

In [1]:
import numpy as np
print("🧮 NumPy Math Operations, Aggregations & Broadcasting\n")

🧮 NumPy Math Operations, Aggregations & Broadcasting



In [2]:
# ✅ 1. Element-wise arithmetic
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a % b:", a % b)
print("a // b:", a // b)
print("a ** 2:", a ** 2)

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a % b: [1 2 3]
a // b: [0 0 0]
a ** 2: [1 4 9]


In [3]:
# ✅ 2. Aggregate functions
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:\n", mat)
print("Sum:", np.sum(mat))
print("Mean:", np.mean(mat))
print("Min:", np.min(mat))
print("Max:", np.max(mat))
print("Std Dev:", np.std(mat))
print("Variance:", np.var(mat))


Matrix:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Mean: 3.5
Min: 1
Max: 6
Std Dev: 1.707825127659933
Variance: 2.9166666666666665


In [4]:
# ✅ 3. Axis-based aggregations
print("\nSum along axis 0 (columns):", np.sum(mat, axis=0))
print("Sum along axis 1 (rows):", np.sum(mat, axis=1))
print("\nMean along axis 0 (columns):", np.mean(mat, axis=0))
print("Mean along axis 1 (rows):", np.mean(mat, axis=1))
print("\nMin along axis 0 (columns):", np.min(mat, axis=0))
print("Min along axis 1 (rows):", np.min(mat, axis=1))
print("\nMax along axis 0 (columns):", np.max(mat, axis=0))
print("Max along axis 1 (rows):", np.max(mat, axis=1))
print("\nStd Dev along axis 0 (columns):", np.std(mat, axis=0))
print("Std Dev along axis 1 (rows):", np.std(mat, axis=1))


Sum along axis 0 (columns): [5 7 9]
Sum along axis 1 (rows): [ 6 15]

Mean along axis 0 (columns): [2.5 3.5 4.5]
Mean along axis 1 (rows): [2. 5.]

Min along axis 0 (columns): [1 2 3]
Min along axis 1 (rows): [1 4]

Max along axis 0 (columns): [4 5 6]
Max along axis 1 (rows): [3 6]

Std Dev along axis 0 (columns): [1.5 1.5 1.5]
Std Dev along axis 1 (rows): [0.81649658 0.81649658]


In [5]:
# ✅ 4. Rounding
arr = np.array([1.234, 5.678, 9.876])
print("\nRounded (2 decimals):", np.round(arr, 2))
print("Floor:", np.floor(arr))
print("Ceil:", np.ceil(arr))
print("Trunc:", np.trunc(arr))


Rounded (2 decimals): [1.23 5.68 9.88]
Floor: [1. 5. 9.]
Ceil: [ 2.  6. 10.]
Trunc: [1. 5. 9.]


In [6]:
# ✅ 5. Exponentials and logarithms
arr = np.array([1, np.e, np.e**2])
print("\nOriginal:", arr)
print("Natural log:", np.log(arr))
print("Base-10 log:", np.log10(arr))
print("Exponential:", np.exp(arr))


Original: [1.         2.71828183 7.3890561 ]
Natural log: [0. 1. 2.]
Base-10 log: [0.         0.43429448 0.86858896]
Exponential: [   2.71828183   15.15426224 1618.17799191]


In [7]:
# ✅ 6. Roots and powers
nums = np.array([4, 9, 16])
print("\nSqrt:", np.sqrt(nums))
print("Cube root:", np.cbrt(nums))
print("Power (nums^3):", np.power(nums, 3))


Sqrt: [2. 3. 4.]
Cube root: [1.58740105 2.08008382 2.5198421 ]
Power (nums^3): [  64  729 4096]


In [8]:
# ✅ 7. Trigonometry
angles = np.array([0, np.pi/2, np.pi])
print("\nSine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Arcsin(1):", np.arcsin(1.0))
print("Degrees:", np.degrees(angles))
print("Radians:", np.radians([0, 90, 180]))


Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Arcsin(1): 1.5707963267948966
Degrees: [  0.  90. 180.]
Radians: [0.         1.57079633 3.14159265]


In [9]:
# ✅ 8. Broadcasting example
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20, 30])     # shape (3,)
broadcasted = a + b
print("\nBroadcasting:\n", broadcasted)


Broadcasting:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [10]:
# ✅ 9. Clipping and absolute
arr = np.array([-10, -2, 0, 4, 12])
print("\nClipped (0 to 10):", np.clip(arr, 0, 10))
print("Absolute:", np.abs(arr))


Clipped (0 to 10): [ 0  0  0  4 10]
Absolute: [10  2  0  4 12]


In [11]:
# ✅ 10. Special: cumulative operations
print("\nCumulative sum:", np.cumsum(arr))
print("Cumulative product:", np.cumprod(arr + 11))  # make all positive to avoid 0


Cumulative sum: [-10 -12 -12  -8   4]
Cumulative product: [    1     9    99  1485 34155]
