# 🧩 Title: Linear Algebra with NumPy

In [1]:
import numpy as np
print("📐 NumPy Linear Algebra Essentials\n")

📐 NumPy Linear Algebra Essentials



In [2]:
# ✅ 1. Dot product (1D & 2D)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot product (1D):", np.dot(a, b))
print("Using @ operator:", a @ b)

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("\nDot product (2D):\n", np.dot(mat1, mat2))
print("Using matmul():\n", np.matmul(mat1, mat2))

Dot product (1D): 32
Using @ operator: 32

Dot product (2D):
 [[19 22]
 [43 50]]
Using matmul():
 [[19 22]
 [43 50]]


In [3]:

# ✅ 2. Matrix transpose
print("\nOriginal matrix:\n", mat1)
print("Transpose:\n", mat1.T)


Original matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]


In [4]:
# ✅ 3. Matrix inverse
square = np.array([[2, 1], [5, 3]])
inv = np.linalg.inv(square)
print("\nMatrix:\n", square)
print("Inverse:\n", inv)



Matrix:
 [[2 1]
 [5 3]]
Inverse:
 [[ 3. -1.]
 [-5.  2.]]


In [5]:
# ✅ 4. Matrix determinant
det = np.linalg.det(square)
print("Determinant:", det)

Determinant: 1.0000000000000002


In [6]:
# ✅ 5. Matrix rank
rank = np.linalg.matrix_rank(square)
print("Rank:", rank)

Rank: 2


In [7]:
# ✅ 6. Eigenvalues and Eigenvectors
eig_vals, eig_vecs = np.linalg.eig(square)
print("\nEigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)


Eigenvalues: [0.20871215 4.79128785]
Eigenvectors:
 [[-0.48744474 -0.33726692]
 [ 0.87315384 -0.94140906]]


In [8]:
# ✅ 7. Norms
v = np.array([3, 4])
print("\nL2 Norm (Euclidean):", np.linalg.norm(v))
print("L1 Norm:", np.linalg.norm(v, ord=1))


L2 Norm (Euclidean): 5.0
L1 Norm: 7.0


In [9]:
# ✅ 8. Solving linear systems
# Solve: Ax = b
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print("\nSolving Ax = b")
print("A:\n", A)
print("b:", b)
print("x:", x)  # should satisfy Ax ≈ b


Solving Ax = b
A:
 [[2 1]
 [1 3]]
b: [ 8 13]
x: [2.2 3.6]


In [10]:
# ✅ 9. Singular Value Decomposition (SVD)
X = np.array([[3, 1, 1], [-1, 3, 1]])
U, S, VT = np.linalg.svd(X)
print("\nMatrix X:\n", X)
print("U:\n", U)
print("Singular values:", S)
print("VT:\n", VT)


Matrix X:
 [[ 3  1  1]
 [-1  3  1]]
U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values: [3.46410162 3.16227766]
VT:
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [11]:
# ✅ 10. Pseudo-inverse (Moore-Penrose)
X_pinv = np.linalg.pinv(X)
print("\nPseudo-inverse of X:\n", X_pinv)


Pseudo-inverse of X:
 [[ 0.28333333 -0.11666667]
 [ 0.06666667  0.26666667]
 [ 0.08333333  0.08333333]]
