# 🧩 Notebook-05: Linear Algebra with NumPy

In [1]:
import sys
from pathlib import Path

# ✅ Project path setup
PROJECT_ROOT = Path.cwd().parent
SCRIPT_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

# ✅ Imports
import numpy as np
from linear_algebra_utils import (
    dot_product, matmul_product, transpose,
    compute_inverse, compute_determinant, compute_rank,
    eigen_decomposition,
    l2_norm, l1_norm,
    solve_system,
    compute_svd,
    pseudo_inverse,
    print_matrix_with_header
)

print("📐 NumPy Linear Algebra Essentials\n")

📐 NumPy Linear Algebra Essentials



In [2]:
# ✅ 1. Dot product (1D & 2D)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot product (1D):", dot_product(a, b))
print("Using @ operator:", a @ b)

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("\nDot product (2D):\n", dot_product(mat1, mat2))
print("Using matmul():\n", matmul_product(mat1, mat2))

Dot product (1D): 32
Using @ operator: 32

Dot product (2D):
 [[19 22]
 [43 50]]
Using matmul():
 [[19 22]
 [43 50]]


In [3]:
# ✅ 2. Matrix transpose
print_matrix_with_header(mat1, "Original Matrix")
print_matrix_with_header(transpose(mat1), "Transpose")


🧾 Original Matrix:
[[1 2]
 [3 4]]

🧾 Transpose:
[[1 3]
 [2 4]]


In [4]:
# ✅ 3. Matrix inverse
square = np.array([[2, 1], [5, 3]])
print_matrix_with_header(square, "Matrix")
print_matrix_with_header(compute_inverse(square), "Inverse")


🧾 Matrix:
[[2 1]
 [5 3]]

🧾 Inverse:
[[ 3. -1.]
 [-5.  2.]]


In [5]:
# ✅ 4. Matrix determinant
print("Determinant:", compute_determinant(square))

Determinant: 1.0000000000000002


In [6]:
# ✅ 5. Matrix rank
print("Rank:", compute_rank(square))

Rank: 2


In [7]:
# ✅ 6. Eigenvalues and Eigenvectors
eig_vals, eig_vecs = eigen_decomposition(square)
print("\nEigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)


Eigenvalues: [0.20871215 4.79128785]
Eigenvectors:
 [[-0.48744474 -0.33726692]
 [ 0.87315384 -0.94140906]]


In [8]:
# ✅ 7. Norms
v = np.array([3, 4])
print("\nL2 Norm (Euclidean):", l2_norm(v))
print("L1 Norm:", l1_norm(v))


L2 Norm (Euclidean): 5.0
L1 Norm: 7.0


In [9]:
# ✅ 8. Solving linear systems
A = np.array([[2, 1], [1, 3]])
b_vec = np.array([8, 13])
x = solve_system(A, b_vec)
print("\nSolving Ax = b")
print_matrix_with_header(A, "A")
print("b:", b_vec)
print("x:", x)  # Should satisfy Ax ≈ b


Solving Ax = b

🧾 A:
[[2 1]
 [1 3]]
b: [ 8 13]
x: [2.2 3.6]


In [10]:
# ✅ 9. Singular Value Decomposition (SVD)
X = np.array([[3, 1, 1], [-1, 3, 1]])
U, S, VT = compute_svd(X)
print_matrix_with_header(X, "Matrix X")
print_matrix_with_header(U, "U (Left Singular Vectors)")
print("Singular values:", S)
print_matrix_with_header(VT, "VT (Right Singular Vectors Transposed)")


🧾 Matrix X:
[[ 3  1  1]
 [-1  3  1]]

🧾 U (Left Singular Vectors):
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values: [3.46410162 3.16227766]

🧾 VT (Right Singular Vectors Transposed):
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [11]:
# ✅ 10. Pseudo-inverse
print_matrix_with_header(pseudo_inverse(X), "Pseudo-Inverse of X")


🧾 Pseudo-Inverse of X:
[[ 0.28333333 -0.11666667]
 [ 0.06666667  0.26666667]
 [ 0.08333333  0.08333333]]


In [12]:
# ✅ 11. Trace of a matrix
trace_val = np.trace(square)
print("\nTrace of matrix:", trace_val)


Trace of matrix: 5


In [13]:
# ✅ 12. Diagonal & identity matrix
diag_elements = np.diag([10, 20, 30])
identity_matrix = np.eye(3)

print_matrix_with_header(diag_elements, "Diagonal Matrix")
print_matrix_with_header(identity_matrix, "Identity Matrix (3x3)")


🧾 Diagonal Matrix:
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]

🧾 Identity Matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# ✅ 13. Rank-1 update (outer product)
u = np.array([[1], [2], [3]])  # shape (3,1)
v = np.array([[4, 5, 6]])      # shape (1,3)
rank1_update = np.dot(u, v)
print_matrix_with_header(rank1_update, "Rank-1 Update via Outer Product (u @ v)")


🧾 Rank-1 Update via Outer Product (u @ v):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [15]:
# ✅ 14. Check symmetric & orthogonal
sym_matrix = np.array([[1, 2], [2, 1]])
is_symmetric = np.allclose(sym_matrix, sym_matrix.T)
print("\nIs symmetric matrix:", is_symmetric)

# Orthogonal: A.T @ A = I
Q, _ = np.linalg.qr(np.random.rand(3, 3))
is_orthogonal = np.allclose(Q.T @ Q, np.eye(3))
print("Is orthogonal matrix (QR-Q):", is_orthogonal)


Is symmetric matrix: True
Is orthogonal matrix (QR-Q): True


In [16]:
# ✅ 15. QR Decomposition
Q, R = np.linalg.qr(X)
print_matrix_with_header(Q, "Q from QR Decomposition")
print_matrix_with_header(R, "R from QR Decomposition")


🧾 Q from QR Decomposition:
[[-0.9486833   0.31622777]
 [ 0.31622777  0.9486833 ]]

🧾 R from QR Decomposition:
[[-3.16227766e+00 -6.41188131e-17 -6.32455532e-01]
 [ 0.00000000e+00  3.16227766e+00  1.26491106e+00]]
