# 🧩 Title: File I/O, Memory Mapping, Views vs Copies in NumPy

In [1]:
import numpy as np
import os

print("💾 NumPy File I/O & Memory Management\n")

💾 NumPy File I/O & Memory Management



In [2]:
# ✅ 1. Saving and loading .npy files
arr = np.arange(10)
# /Users/satvikpraveen/Desktop/Libraries/NumPyMasteryPro/datasets
path = "/Users/satvikpraveen/Desktop/Libraries/NumPyMasteryPro/datasets/"
np.save(path + "sample_array.npy", arr)
loaded = np.load(path + "sample_array.npy")
print("Saved .npy array:", loaded)

Saved .npy array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# ✅ 2. Saving and loading multiple arrays (.npz format)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
path = "/Users/satvikpraveen/Desktop/Libraries/NumPyMasteryPro/datasets/"
np.savez(path+"multiple_arrays.npz", array1=a, array2=b)
data = np.load(path+"multiple_arrays.npz")
print("\nArray1 from .npz:", data["array1"])
print("Array2 from .npz:", data["array2"])


Array1 from .npz: [1 2 3]
Array2 from .npz: [4 5 6]


In [4]:
# ✅ 3. Saving to and loading from text
np.savetxt(path+"sample_data.txt", arr, delimiter=",")
loaded_txt = np.loadtxt(path+"sample_data.txt", delimiter=",")
print("\nLoaded from .txt:", loaded_txt)


Loaded from .txt: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
# ✅ 4. Using genfromtxt (handling missing data)
with open(path+"missing_data.csv", "w") as f:
    f.write("1.0, 2.0, 3.0\n4.0, , 6.0\n7.0, 8.0, 9.0")
data = np.genfromtxt(path+"missing_data.csv", delimiter=",")
print("\nData with missing value handled:\n", data)


Data with missing value handled:
 [[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [6]:
# ✅ 5. Memory-mapped files (efficient large file I/O)
mmap_array = np.memmap(path+"memmap_array.dat", dtype='float32', mode='w+', shape=(3, 3))
mmap_array[:] = np.random.rand(3, 3)
print("\nMemory-mapped array:\n", mmap_array)
del mmap_array  # flush data


Memory-mapped array:
 [[0.99970555 0.10805134 0.3831926 ]
 [0.2796911  0.7462194  0.47375485]
 [0.20897995 0.17428382 0.46663654]]


In [7]:
# ✅ 6. Reload memory-mapped array
mmap_loaded = np.memmap(path+"memmap_array.dat", dtype='float32', mode='r', shape=(3, 3))
print("Reloaded memmap array:\n", mmap_loaded)

Reloaded memmap array:
 [[0.99970555 0.10805134 0.3831926 ]
 [0.2796911  0.7462194  0.47375485]
 [0.20897995 0.17428382 0.46663654]]


In [8]:
# ✅ 7. Views vs. Copies
arr = np.array([1, 2, 3])
view = arr.view()
copy = arr.copy()
arr[0] = 100

print("\nOriginal array modified:", arr)
print("View (shares memory):", view)
print("Copy (independent):", copy)


Original array modified: [100   2   3]
View (shares memory): [100   2   3]
Copy (independent): [1 2 3]


In [9]:
# ✅ 8. Check memory sharing
print("arr.base is None:", arr.base is None)
print("view.base is arr:", view.base is arr)
print("copy.base is None:", copy.base is None)

arr.base is None: True
view.base is arr: True
copy.base is None: True


In [10]:
# ✅ 9. Using np.vectorize() to apply custom functions element-wise
def safe_divide(x, y):
    return 0 if y == 0 else x / y

# Example arrays
a = np.array([10, 20, 30])
b = np.array([2, 0, 5])

vec_divide = np.vectorize(safe_divide)
print("\nVectorized divide:", vec_divide(a, b))


Vectorized divide: [5. 0. 6.]
