# 🧩 Title: Real-World Use Cases with NumPy

In [1]:
import numpy as np

print("🌍 Real-World Use Cases with NumPy\n")

🌍 Real-World Use Cases with NumPy



In [ ]:
# ✅ 1. Linear Regression (Closed-form using Matrix Math)
# y = X @ w + b → w = (XᵀX)^(-1)Xᵀy
np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

# Add bias term (intercept) manually
X_b = np.c_[np.ones((100, 1)), X]       # Add bias term (column of ones)

# Compute parameters
theta_best = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
print("Best fit (intercept, slope):", theta_best.ravel())

Best fit (intercept, slope): [4.22215108 2.96846751]


In [4]:
# ✅ 2. Image manipulation (mock grayscale image)
img = np.random.randint(0, 256, size=(5, 5), dtype=np.uint8)
print("\nOriginal Image (5x5 grayscale):\n", img)

# Flip image horizontally
flipped = np.fliplr(img)
print("Horizontally Flipped:\n", flipped)

# Rotate 90 degrees
rotated = np.rot90(img)
print("Rotated 90°:\n", rotated)

# Normalize image (0–1)
normalized = img / 255.0
print("Normalized:\n", normalized.round(2))


Original Image (5x5 grayscale):
 [[ 83 194  28  53 135]
 [130  88  39 200  47]
 [184 108  61  66 254]
 [186 141 154 201  95]
 [  5 150 113 165   0]]
Horizontally Flipped:
 [[135  53  28 194  83]
 [ 47 200  39  88 130]
 [254  66  61 108 184]
 [ 95 201 154 141 186]
 [  0 165 113 150   5]]
Rotated 90°:
 [[135  47 254  95   0]
 [ 53 200  66 201 165]
 [ 28  39  61 154 113]
 [194  88 108 141 150]
 [ 83 130 184 186   5]]
Normalized:
 [[0.33 0.76 0.11 0.21 0.53]
 [0.51 0.35 0.15 0.78 0.18]
 [0.72 0.42 0.24 0.26 1.  ]
 [0.73 0.55 0.6  0.79 0.37]
 [0.02 0.59 0.44 0.65 0.  ]]


## 🎲 Monte Carlo Simulation: Estimating π

This simulation uses the Monte Carlo method to approximate the value of π.

### 🧠 Concept

Imagine a **unit square** of side 1, and inscribe a **quarter circle** of radius 1 inside it.

- **Area of the square** = 1 × 1 = 1  
- **Area of the quarter circle** = (π × r²) / 4 = π / 4 (since r = 1)

Now, if we throw random (x, y) points inside the square, the ratio of points falling inside the quarter circle will approximate the ratio of the two areas:

$$\frac{\text{Points inside quarter circle}}{\text{Total points}} \approx \frac{\pi}{4}$$


So,

$$\pi \approx 4 \times \left(\frac{\text{Points inside}}{N}\right)$$

---

In [5]:
# ✅ 3. Monte Carlo Simulation: π approximation
N = 1000000
x = np.random.rand(N)
y = np.random.rand(N)
inside_circle = (x**2 + y**2) <= 1
pi_estimate = 4 * np.mean(inside_circle)
print("\nMonte Carlo π estimate (N=1,000,000):", pi_estimate)


Monte Carlo π estimate (N=1,000,000): 3.138292


## 📈 Broadcasting for Time-Series Standardization

This example demonstrates how to use **NumPy broadcasting** to **standardize multivariate time-series data** — such as readings from multiple sensors over time.

---

### 🧠 Problem Statement

We have `signals` from **3 different sensors**, each sampled across **10 time points**.  
We want to **standardize** each sensor's data (i.e., each row) so it has:

- **Mean = 0**
- **Standard Deviation = 1**

This is essential for preprocessing time-series data before applying ML models or statistical analysis.

---

In [6]:
# ✅ 4. Broadcasting for time-series scaling
signals = np.random.rand(3, 10)  # 3 sensors × 10 timepoints
means = signals.mean(axis=1, keepdims=True)
stds = signals.std(axis=1, keepdims=True)
standardized = (signals - means) / stds
print("\nStandardized time-series shape:", standardized.shape)


Standardized time-series shape: (3, 10)


In [7]:
# ✅ 5. Financial simulation: Compound growth
years = np.arange(1, 11)
principal = 1000
rate = 0.08
amount = principal * (1 + rate) ** years
print("\nCompound Interest Over 10 Years:\n", amount.round(2))


Compound Interest Over 10 Years:
 [1080.   1166.4  1259.71 1360.49 1469.33 1586.87 1713.82 1850.93 1999.
 2158.92]


In [8]:
# ✅ 6. Apply custom function along axis
def range_of_row(row):
    return row.max() - row.min()

mat = np.array([[2, 7, 4],
                [10, 15, 5],
                [6, 9, 3]])

row_ranges = np.apply_along_axis(range_of_row, axis=1, arr=mat)
print("\nRange of each row (max - min):", row_ranges)


Range of each row (max - min): [ 5 10  6]
